- name: Run vulnerability scan
  hosts: all
  tasks:
    - name: Install nmap
      apt:
        name: nmap
        state: present

    - name: Run nmap scan
      command: nmap -sV {{ inventory_hostname }} >> /var/log/nmap_scan.log
